### ISSUE TITLE
Nullable lists are transformed into non-nullable lists

### ISSUE THREAD

**Issue by feedm3** [gatsbyjs/gatsby-graphql-toolkit#39]
## The problem

A bug in the `gatsby-graphql-toolkit` transforms a nullable list from the API into a non-nullable list within the internal Gatsby GraphQL API. Additionally, if the list entry is non-nullable it will become nullable. The null operator gets flipped between the list and the entry.

This makes using nullable lists impossible. As soon as the API will deliver `null` instead of an empty array, Gatsby fails with an error during sourcing saying this is an invalid value (although it is not).

## Example 

Let's say the Graphql API looks like this:

```gql
type Type {
  list: [Entry!]
}
```

If we query the `__schema` field, we get the following result:

```json
 {
  "name": "list",
  "type": {
    "kind": "LIST",
    "name": null,
    "ofType": {
      "kind": "NON_NULL",
      "name": null,
      "ofType": {
        "name": "Entry",
        "kind": "OBJECT",
        "ofType": null
      }
    }
  }
},
```

This is all correct. Now we take the `gatsby-graphql-toolkit` to add the Type to our Gatsby store. This will transform the `list` into a wrong type:

```gql
type GatsbyType {
  list: [GatsbyEntry]!
}
```

With the `__schema` result:

```json
{
  "name": "list",
  "type": {
    "kind": "NON_NULL",
    "name": null,
    "ofType": {
      "kind": "LIST",
      "name": null,
      "ofType": {
        "name": "GatsbyEntry",
        "kind": "OBJECT",
        "ofType": null
      }
    }
  }
}
```

**Comment by Leksat** [comment]
Confirming. Source `field: [Type]!` is translated to `field: [Type!]`.

**Comment by andrezimpel** [comment]
Can confirm. Schema customization doesn't seam to be a way to work around this.

**Comment by andrezimpel** [comment]
> Type conversion usually happens here:
> 
> https://github.com/gatsbyjs/gatsby-graphql-toolkit/blob/c9328e2cae08acb45faf6f7a28fb6e033be4db33/src/create-schema-customization/transform-fields/field-transformers.ts#L156-L184

@vladar so does this mean `isListType` or `isNonNullType` is not correct, right?

**Comment by Leksat** [comment]
Could someone take a look at the PR? https://github.com/gatsbyjs/gatsby-graphql-toolkit/pull/87

**Comment by Leksat** [comment]
A release? 🙏 

(This is a really confusing bug 😅)
