### ISSUE TITLE
GraphQL 16 compatibility

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby-graphql-toolkit#47]
Make the toolkit compatible with GQL 16.

The only problem I see is this visitor, which is causing `TypeError: visitFn.call is not a function`:

https://github.com/gatsbyjs/gatsby-graphql-toolkit/blob/b395feb66b2c1505a27696a0b3c8a214806b94bd/src/compile-node-queries/ast-transformers/remove-unused-fragments.ts#L11-L42

Support for `enter` and `leave` objects was dropped in GraphQL 16 (https://github.com/graphql/graphql-js/pull/2957), so the visitor would just need to be rewritten in this format:

```ts
visit(ast, {
  Kind: {
    enter(node) {
      // enter the "Kind" node
    }
    leave(node) {
      // leave the "Kind" node
    }
  }
})
```

I've patched this locally, and otherwise everything seems to be working fine.

**Comment by cameronbraid** [comment]
This is also needed for gatsby 5
